version: 2.1
jobs:
  build:
    docker:
      - image: checkmarx/ast-cli
    steps:
      - checkout
      - run:
          name: "Run Scan"
          command: |
            /app/bin/cx \
            scan create \
            -s https://github.com/AASMACMX/DSVW_SCS.git \
            --client-id $CX_CLIENT_ID \
            --client-secret $CX_CLIENT_SECRET \
            --tenant $CX_TENANT \
            -base-uri $CX_BASE_URI \
            --base-auth-uri $CX_BASE_AUTH_URI \
            --agent CircleCI \
            --project-name TEST \
            --branch develop \

            

