version: 2.1
jobs:
  build:
    docker:
      - image: checkmarx/ast-cli
    steps:
      - checkout
      - run:
          name: "Run Scan"
          command: |
            /app/bin/cx \
            scan create \
            -s ./ \
            --agent CircleCI \
            --project-name $PROJECT \
            --branch develop \
            --base-uri $CX_BASE_URI \
            --base-auth-uri $CX_BASE_AUTH_URI \
            --tenant $CX_TENANT \
            --apikey $CX_API_KEY \
            --async
