# This is a basic workflow to help you get started with Actions
name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Cxflow Action
      - name: Checkmarx CxFlow Action
        # You may pin to the exact commit or the version.
        # uses: checkmarx-ts/checkmarx-cxflow-github-action@95d2a8c86d754ddbccc638a7e1bb8e99a8d2244f
        uses: checkmarx-ts/checkmarx-cxflow-github-action@v1.0
        with:
          # Provide Checkmarx URL
          checkmarx_url: https://blueprism.checkmarx.net
          # Provide team
          team: /CxServer
          # Provide Checkmarx Username
          checkmarx_username: cxsupport@checkmarx.com
          # Provide Checkmarx Password
          checkmarx_password: Hbon38]ttZThU!0
          # Provide Checkmarx Client Secret
          checkmarx_client_secret: 014DF517-39D1-4453-B7B3-9930C563627C
          # Select a Checkmarx Project
          project: DSVW-GitHub-action
          # Select an Application Name used by downstream bug tracker systems
          app: DSVW
          # Select a Checkmarx Preset
          #preset: # optional, default is Checkmarx Default
          # Break build based on Checkmarx findings?
          #break_build: # optional
          # Incremental Scans?
          incremental: true
          # GitHub API Token
          github_token: ${{secrets.MY_GITHUB_TOKEN}}
          params: --checkmarx.version=9.0 --checkmarx.scope=[access_control_api sast_rest_api] --checkmarx.base-url=https://blueprism.checkmarx.net --checkmarx.url=https://blueprism.checkmarx.net/cxrestapi --checkmarx.portal-url=https://blueprism.checkmarx.net/cxwebinterface/Portal/CxWebService.asmx --checkmarx.sdk-url=https://blueprism.checkmarx.net/cxwebinterface/SDK/CxSDKWebService.asmx --checkmarx.portal-wsdl=https://blueprism.checkmarx.net/Portal/CxWebService.asmx?wsdl --checkmarx.sdk-wsdl=https://blueprism.checkmarx.net/SDK/CxSDKWebService.asmx?wsdl
